# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wenjuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=32)),
                ('post_time', models.DateTimeField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('placeRadio', models.CharField(db_index=True, max_length=2)),
                ('placetyped', models.CharField(db_index=True, max_length=32)),
                ('beforeAction', models.CharField(db_index=True, max_length=2)),
                ('jacket', models.CharField(db_index=True, max_length=2)),
                ('trousers', models.CharField(db_index=True, max_length=2)),
                ('temperature', models.CharField(db_index=True, max_length=2)),
                ('confortable', models.CharField(db_index=True, max_length=2)),
                ('totalconf', models.CharField(db_index=True, max_length=2)),
                ('beats', models.CharField(db_index=True, max_length=3)),
                ('lat', models.FloatField(db_index=True, default=0)),
                ('lon', models.FloatField(db_index=True, default=0)),
            ],
        ),
    ]
